### ISSUE TITLE
How can we execute or install de tool?

### ISSUE THREAD

**Issue by fjrodriguez** [showmik/furigana-tool#1]
I saw that the code is in Visual Basic, but I don't know how to install or execute it.

Thanks.

**Comment by showmik** [comment]
Hi @fjrodriguez 

Just download [this file](https://github.com/showmik/furigana-tool/releases/download/1.0.0/furigana-tool.zip) and then unzip it. There's an executable (FuriganaTool.exe) file in it. Just run this file and you will be able to use the tool.

**Comment by fjrodriguez** [comment]
Hi @showmik 

It worked for me. When I execute the program Windows popup a security message because the author is unknowed. If I click in "more information" then I can execute the program. Thank you very much and good job.
